disabled_rules:
  - function_body_length
opt_in_rules:
  - file_name
  - file_name_no_space
  - sorted_imports
  - unused_import
excluded:
  - Carthage
  - Pods
line_length:
  - 200 # warning
  - 300 # error
